apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.applicationName | lower}}-config
  namespace: {{.Values.projectNamespace | lower}}
data:
  log-config: {{.Values.config.logConfig | quote }}
  app-config: {{.Values.config.appConfig | quote }}